//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuilderProjectConfig
    {
        public BuilderProjectConfig()
        {
            this.BuilderProjectFloorPlan = new HashSet<BuilderProjectFloorPlan>();
            this.BuilderProjectSubConfig = new HashSet<BuilderProjectSubConfig>();
        }
    
        public decimal BuilderProjectConfigId { get; set; }
        public Nullable<decimal> BuilderProjectId { get; set; }
        public Nullable<decimal> mPropConfigId { get; set; }
        public Nullable<decimal> ProjectConfigAreaMin { get; set; }
        public Nullable<decimal> ProjectConfigAreaMax { get; set; }
        public Nullable<decimal> ProjectConfigMinPrice { get; set; }
        public Nullable<decimal> ProjectConfigMaxPrice { get; set; }
    
        public virtual mBuilderProjects mBuilderProjects { get; set; }
        public virtual mPropConfig mPropConfig { get; set; }
        public virtual ICollection<BuilderProjectFloorPlan> BuilderProjectFloorPlan { get; set; }
        public virtual ICollection<BuilderProjectSubConfig> BuilderProjectSubConfig { get; set; }
    }
}
