//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalityDetails
    {
        public LocalityDetails()
        {
            this.LocalityBlock = new HashSet<LocalityBlock>();
            this.LocalityDetailsCommute = new HashSet<LocalityDetailsCommute>();
            this.LocalityKeyHighLights = new HashSet<LocalityKeyHighLights>();
            this.LocalityGreatPlaces = new HashSet<LocalityGreatPlaces>();
            this.LocalityTags = new HashSet<LocalityTags>();
        }
    
        public decimal LocalityDetailsId { get; set; }
        public decimal mLocalityID { get; set; }
        public string GoogleMap { get; set; }
        public string GoogleMapDescription { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<LocalityBlock> LocalityBlock { get; set; }
        public virtual ICollection<LocalityDetailsCommute> LocalityDetailsCommute { get; set; }
        public virtual ICollection<LocalityKeyHighLights> LocalityKeyHighLights { get; set; }
        public virtual ICollection<LocalityGreatPlaces> LocalityGreatPlaces { get; set; }
        public virtual ICollection<LocalityTags> LocalityTags { get; set; }
    }
}
