//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mCategoryOfExternalAmenities
    {
        public mCategoryOfExternalAmenities()
        {
            this.BuilderProjExternalAmenities = new HashSet<BuilderProjExternalAmenities>();
        }
    
        public decimal mCategoryOfExternalAmenities1 { get; set; }
        public Nullable<decimal> mNeighbourHoodId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDesc { get; set; }
    
        public virtual ICollection<BuilderProjExternalAmenities> BuilderProjExternalAmenities { get; set; }
        public virtual mNeighbourHoodTags mNeighbourHoodTags { get; set; }
    }
}
