//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mLocality
    {
        public mLocality()
        {
            this.LocalityBlock = new HashSet<LocalityBlock>();
            this.LocalityDetailsCommute = new HashSet<LocalityDetailsCommute>();
            this.LocalityGallery = new HashSet<LocalityGallery>();
            this.LocalityGreatPlaces = new HashSet<LocalityGreatPlaces>();
            this.LocalityKeyHighLights = new HashSet<LocalityKeyHighLights>();
            this.LocalitySuggestions = new HashSet<LocalitySuggestions>();
            this.LocalityTags = new HashSet<LocalityTags>();
            this.mBuildings = new HashSet<mBuildings>();
            this.PropscoutWorkAreas = new HashSet<PropscoutWorkAreas>();
            this.mSociety = new HashSet<mSociety>();
        }
    
        public decimal mLocalityId { get; set; }
        public Nullable<decimal> mCityId { get; set; }
        public string LocalityName { get; set; }
        public Nullable<decimal> LocalityZipCode { get; set; }
        public string LocalityThumbnail { get; set; }
        public string LocalityShortDesc { get; set; }
        public string LocalityLongDesc { get; set; }
        public Nullable<decimal> PropMinimumPrice { get; set; }
        public Nullable<decimal> PropMaximumPrice { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> CreadtedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<LocalityBlock> LocalityBlock { get; set; }
        public virtual ICollection<LocalityDetailsCommute> LocalityDetailsCommute { get; set; }
        public virtual ICollection<LocalityGallery> LocalityGallery { get; set; }
        public virtual ICollection<LocalityGreatPlaces> LocalityGreatPlaces { get; set; }
        public virtual ICollection<LocalityKeyHighLights> LocalityKeyHighLights { get; set; }
        public virtual ICollection<LocalitySuggestions> LocalitySuggestions { get; set; }
        public virtual ICollection<LocalityTags> LocalityTags { get; set; }
        public virtual ICollection<mBuildings> mBuildings { get; set; }
        public virtual mCity mCity { get; set; }
        public virtual ICollection<PropscoutWorkAreas> PropscoutWorkAreas { get; set; }
        public virtual ICollection<mSociety> mSociety { get; set; }
    }
}
