//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropscoutProfile
    {
        public PropscoutProfile()
        {
            this.PropscoutWorkAreas = new HashSet<PropscoutWorkAreas>();
        }
    
        public decimal PropscoutId { get; set; }
        public string PropscoutName { get; set; }
        public string SelfIntroduction { get; set; }
        public Nullable<decimal> UserCredentialsId { get; set; }
        public string Designation { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<decimal> NoOfProeprtiesSold { get; set; }
    
        public virtual UserCredential UserCredential { get; set; }
        public virtual ICollection<PropscoutWorkAreas> PropscoutWorkAreas { get; set; }
    }
}
