//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTagPreferences
    {
        public Nullable<decimal> UserTagID { get; set; }
        public decimal BuildingPrefID { get; set; }
        public Nullable<decimal> UserID { get; set; }
        public string TagPreferencesID { get; set; }
        public Nullable<System.DateTime> CreatedDatettime { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
